use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatformDefinition {
    pub id: String,
    pub name: String,
    pub icon: String,
    pub base_url: String,
    pub api_key_required: bool,
    pub api_key_url: String,
    pub description: String,
    pub models: Vec<ModelPreset>,
    pub protocol: ApiProtocol,
    pub default_headers: Vec<(String, String)>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ApiProtocol {
    OpenAICompatible,
    Anthropic,
    GoogleGemini,
    Ollama,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelPreset {
    pub id: String,
    pub name: String,
    pub description: String,
    pub max_tokens: u32,
    pub is_recommended: bool,
    pub context_window: u32,
}

pub fn get_builtin_platforms() -> Vec<PlatformDefinition> {
    vec![
        PlatformDefinition {
            id: "openai".into(),
            name: "OpenAI".into(),
            icon: "openai".into(),
            base_url: "https://api.openai.com/v1".into(),
            api_key_required: true,
            api_key_url: "https://platform.openai.com/api-keys".into(),
            description: "GPT-4o、GPT-4o-mini 等模型，全球最广泛使用的 AI 平台".into(),
            protocol: ApiProtocol::OpenAICompatible,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "gpt-4o-mini".into(),
                    name: "GPT-4o Mini".into(),
                    description: "性价比最高，适合 SQL 生成和代码任务".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 128000,
                },
                ModelPreset {
                    id: "gpt-4o".into(),
                    name: "GPT-4o".into(),
                    description: "最强大的模型，复杂查询和分析更准确".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 128000,
                },
                ModelPreset {
                    id: "gpt-4.1-mini".into(),
                    name: "GPT-4.1 Mini".into(),
                    description: "新一代高效模型，编码能力更强".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 1047576,
                },
                ModelPreset {
                    id: "gpt-4.1".into(),
                    name: "GPT-4.1".into(),
                    description: "最新旗舰模型，代码和指令遵循能力极强".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 1047576,
                },
            ],
        },
        PlatformDefinition {
            id: "deepseek".into(),
            name: "DeepSeek".into(),
            icon: "deepseek".into(),
            base_url: "https://api.deepseek.com/v1".into(),
            api_key_required: true,
            api_key_url: "https://platform.deepseek.com/api_keys".into(),
            description: "国产高性价比模型，代码和推理能力出色，价格极低".into(),
            protocol: ApiProtocol::OpenAICompatible,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "deepseek-chat".into(),
                    name: "DeepSeek-V3".into(),
                    description: "通用对话模型，SQL 生成性价比之王".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 65536,
                },
                ModelPreset {
                    id: "deepseek-reasoner".into(),
                    name: "DeepSeek-R1".into(),
                    description: "深度推理模型，适合复杂 SQL 逻辑分析".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 65536,
                },
            ],
        },
        PlatformDefinition {
            id: "anthropic".into(),
            name: "Anthropic".into(),
            icon: "anthropic".into(),
            base_url: "https://api.anthropic.com/v1".into(),
            api_key_required: true,
            api_key_url: "https://console.anthropic.com/settings/keys".into(),
            description: "Claude 系列模型，长上下文和代码理解能力顶尖".into(),
            protocol: ApiProtocol::Anthropic,
            default_headers: vec![
                ("anthropic-version".into(), "2023-06-01".into()),
            ],
            models: vec![
                ModelPreset {
                    id: "claude-sonnet-4-20250514".into(),
                    name: "Claude Sonnet 4".into(),
                    description: "最新平衡模型，性能与成本兼顾".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 200000,
                },
                ModelPreset {
                    id: "claude-3-5-haiku-20241022".into(),
                    name: "Claude 3.5 Haiku".into(),
                    description: "速度最快，适合简单 SQL 生成".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 200000,
                },
            ],
        },
        PlatformDefinition {
            id: "google".into(),
            name: "Google Gemini".into(),
            icon: "google".into(),
            base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
            api_key_required: true,
            api_key_url: "https://aistudio.google.com/apikey".into(),
            description: "Google Gemini 系列，支持超长上下文".into(),
            protocol: ApiProtocol::GoogleGemini,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "gemini-2.0-flash".into(),
                    name: "Gemini 2.0 Flash".into(),
                    description: "最新高速模型，免费额度慷慨".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 1048576,
                },
                ModelPreset {
                    id: "gemini-2.5-pro-preview-06-05".into(),
                    name: "Gemini 2.5 Pro".into(),
                    description: "最强大模型，复杂推理和代码能力一流".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 1048576,
                },
            ],
        },
        PlatformDefinition {
            id: "qwen".into(),
            name: "通义千问".into(),
            icon: "qwen".into(),
            base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1".into(),
            api_key_required: true,
            api_key_url: "https://bailian.console.aliyun.com/?apiKey=1".into(),
            description: "阿里通义千问，国内访问速度快，中文理解能力强".into(),
            protocol: ApiProtocol::OpenAICompatible,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "qwen-plus".into(),
                    name: "Qwen Plus".into(),
                    description: "性价比高，适合日常 SQL 生成".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 131072,
                },
                ModelPreset {
                    id: "qwen-max".into(),
                    name: "Qwen Max".into(),
                    description: "最强能力，复杂任务首选".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 32768,
                },
                ModelPreset {
                    id: "qwen-turbo".into(),
                    name: "Qwen Turbo".into(),
                    description: "速度最快，成本最低".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 131072,
                },
            ],
        },
        PlatformDefinition {
            id: "moonshot".into(),
            name: "Moonshot (Kimi)".into(),
            icon: "moonshot".into(),
            base_url: "https://api.moonshot.cn/v1".into(),
            api_key_required: true,
            api_key_url: "https://platform.moonshot.cn/console/api-keys".into(),
            description: "月之暗面 Kimi，超长上下文，中文能力优秀".into(),
            protocol: ApiProtocol::OpenAICompatible,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "moonshot-v1-8k".into(),
                    name: "Moonshot v1 8K".into(),
                    description: "适合简单 SQL 任务，成本低".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 8192,
                },
                ModelPreset {
                    id: "moonshot-v1-32k".into(),
                    name: "Moonshot v1 32K".into(),
                    description: "更长上下文，适合复杂 schema".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 32768,
                },
            ],
        },
        PlatformDefinition {
            id: "zhipu".into(),
            name: "智谱 AI".into(),
            icon: "zhipu".into(),
            base_url: "https://open.bigmodel.cn/api/paas/v4".into(),
            api_key_required: true,
            api_key_url: "https://open.bigmodel.cn/usercenter/apikeys".into(),
            description: "智谱 GLM 系列，国内老牌 AI 平台".into(),
            protocol: ApiProtocol::OpenAICompatible,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "glm-4-flash".into(),
                    name: "GLM-4 Flash".into(),
                    description: "高速模型，免费使用".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 128000,
                },
                ModelPreset {
                    id: "glm-4-plus".into(),
                    name: "GLM-4 Plus".into(),
                    description: "增强版，更准确的代码理解".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 128000,
                },
            ],
        },
        PlatformDefinition {
            id: "baichuan".into(),
            name: "百川智能".into(),
            icon: "baichuan".into(),
            base_url: "https://api.baichuan-ai.com/v1".into(),
            api_key_required: true,
            api_key_url: "https://platform.baichuan-ai.com/console/apikey".into(),
            description: "百川大模型，中文理解和生成能力突出".into(),
            protocol: ApiProtocol::OpenAICompatible,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "Baichuan4-Air".into(),
                    name: "Baichuan4 Air".into(),
                    description: "轻量高效，适合 SQL 场景".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 32768,
                },
                ModelPreset {
                    id: "Baichuan4".into(),
                    name: "Baichuan4".into(),
                    description: "旗舰模型，综合能力最强".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 32768,
                },
            ],
        },
        PlatformDefinition {
            id: "yi".into(),
            name: "零一万物".into(),
            icon: "yi".into(),
            base_url: "https://api.lingyiwanwu.com/v1".into(),
            api_key_required: true,
            api_key_url: "https://platform.lingyiwanwu.com/apikeys".into(),
            description: "Yi 系列模型，开源基因，性能优秀".into(),
            protocol: ApiProtocol::OpenAICompatible,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "yi-lightning".into(),
                    name: "Yi Lightning".into(),
                    description: "超高速推理，性价比极高".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 16384,
                },
                ModelPreset {
                    id: "yi-large".into(),
                    name: "Yi Large".into(),
                    description: "大参数量，复杂任务更准确".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 32768,
                },
            ],
        },
        PlatformDefinition {
            id: "ollama".into(),
            name: "Ollama (本地)".into(),
            icon: "ollama".into(),
            base_url: "http://localhost:11434/v1".into(),
            api_key_required: false,
            api_key_url: "https://ollama.com/download".into(),
            description: "本地运行开源模型，完全离线，数据零泄露".into(),
            protocol: ApiProtocol::Ollama,
            default_headers: vec![],
            models: vec![
                ModelPreset {
                    id: "qwen2.5-coder:7b".into(),
                    name: "Qwen2.5 Coder 7B".into(),
                    description: "专为代码优化，SQL 生成能力强，推荐 16GB+ 内存".into(),
                    max_tokens: 4096,
                    is_recommended: true,
                    context_window: 32768,
                },
                ModelPreset {
                    id: "llama3.1:8b".into(),
                    name: "Llama 3.1 8B".into(),
                    description: "Meta 开源模型，通用能力均衡".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 131072,
                },
                ModelPreset {
                    id: "codellama:7b".into(),
                    name: "Code Llama 7B".into(),
                    description: "专注代码任务的 Llama 变体".into(),
                    max_tokens: 4096,
                    is_recommended: false,
                    context_window: 16384,
                },
            ],
        },
        PlatformDefinition {
            id: "custom".into(),
            name: "自定义 API".into(),
            icon: "custom".into(),
            base_url: String::new(),
            api_key_required: false,
            api_key_url: String::new(),
            description: "任何兼容 OpenAI Chat Completions API 格式的服务".into(),
            protocol: ApiProtocol::OpenAICompatible,
            default_headers: vec![],
            models: vec![],
        },
    ]
}
